# Generated by Django 6.0.6 on 2026-09-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0004_ticket_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='priority',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
