# Generated by Django 6.0.6 on 2026-07-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
