# Generated by Django 6.0.6 on 2026-07-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk_auth', '0002_users_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
